# Generated by Django 4.2.1 on 2023-05-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Message content')),
                ('start', models.DateTimeField(verbose_name='Sending starts at')),
                ('finish', models.DateTimeField(verbose_name='Sending finishes at')),
                ('tag', models.CharField(blank=True, max_length=32, null=True, verbose_name='Filter tag')),
                ('operator_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Operator code filter')),
            ],
            options={
                'verbose_name': 'Mailer',
                'verbose_name_plural': 'Mailers',
            },
        ),
    ]
