# Generated by Django 4.2.1 on 2023-05-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='mailer',
        ),
    ]
