# Generated by Django 4.2.1 on 2023-05-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='operator_code',
            field=models.CharField(default='', editable=False, max_length=3, verbose_name='Operator code'),
        ),
    ]
