# Generated by Django 4.2.1 on 2023-05-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sender',
            old_name='operpator_code',
            new_name='operator_code',
        ),
    ]
